"""Write the PROV-N probes to ``provn/probes/<name>.provn``.

Each probe is a short PROV-N text that isolates one production or rule.
``provn/probes/expected.tsv`` holds the result each profile must give.
Run from the repository root:

    python tools/gen_probes.py

The files are written byte for byte (no newline translation), so probes
that test bare CR, CRLF, a byte-order mark or NUL survive on any platform.
"""

from pathlib import Path

P = "prefix ex <http://example.org/>\n"
D = "default <http://d.example/>\n"
X = P + "prefix dictExt <http://example.org/dictionaries#>\n"


def doc(body, decl=P):
    return f"document\n{decl}{body}\nendDocument\n"


probes = {
 # names
 "at_bare_name": doc("entity(@foo)", D),
 "at_prefixed_local": doc("entity(ex:@foo)"),
 "at_attr_value_qname": doc("entity(ex:e, [ex:k='@foo'])", P + D),
 "empty_local": doc("entity(ex:)"),
 "trailing_dot": doc("entity(ex:a.)"),
 "inner_dot": doc("entity(ex:a.b)"),
 "esc_spec_set": doc(r"entity(ex:a\=b\,c\(d\)\;\:\[\]\'\-\.)"),
 "esc_underscore": doc(r"entity(ex:a\_b)"),
 "esc_tilde": doc(r"entity(ex:a\~b)"),
 "esc_slash": doc(r"entity(ex:a\/b)"),
 "esc_percent": doc(r"entity(ex:a\%b)"),
 "esc_at": doc(r"entity(ex:a\@b)"),
 "esc_hash": doc(r"entity(ex:a\#b)"),
 "esc_invalid_q": doc(r"entity(ex:a\qb)"),
 "bare_escaped_colon": doc(r"entity(a\:b)", D),
 "percent_hex": doc("entity(ex:a%2Fb)"),
 "percent_bad": doc("entity(ex:a%zz)"),
 "blank_node": doc("entity(_:x)"),
 "bare_no_default": doc("entity(e)", ""),
 "digit_id": doc("entity(123)", D),
 "digit_id_leading_zero": doc("entity(007)", D),
 "neg_digit_id": doc("entity(-5)", D),
 "digit_attr_name": doc('entity(ex:e, [123="x"])', P + D),
 "digit_datatype": doc('entity(ex:e, [ex:k="x" %% 123])', P + D),
 "digit_prefix": doc("entity(ex:e)", "prefix 1 <http://one/>\n" + P),
 "digit_bundle_id": doc("bundle 12\nendBundle", D),
 "keyword_as_id": doc("entity(bundle)", D),
 "keyword_bundle_id": doc("bundle bundle\nentity(e)\nendBundle", D),
 "unicode_name": doc("entity(ex:caf\xe9\xb7x)"),
 "combining_start": doc("entity(ex:\u0301a)"),
 "ogham_space_in_name": doc("entity(ex:a\u1680b)"),
 # declarations
 "second_default": doc("entity(e)", "default <http://a/>\ndefault <http://b/>\n"),
 "default_after_prefix": doc("entity(e)", P + D),
 "dup_prefix": doc("entity(ex:e)", P + "prefix ex <http://other/>\n"),
 "dup_prefix_same_iri": doc("entity(ex:e)", P + P),
 "prov_redeclared_other": doc("entity(ex:e)", P + "prefix prov <http://other/>\n"),
 "prov_redeclared_same": doc("entity(ex:e)", P + "prefix prov <http://www.w3.org/ns/prov#>\n"),
 "xsd_redeclared_no_hash": doc("entity(ex:e)", P + "prefix xsd <http://www.w3.org/2001/XMLSchema>\n"),
 "xsd_redeclared_same": doc("entity(ex:e)", P + "prefix xsd <http://www.w3.org/2001/XMLSchema#>\n"),
 "xsi_undeclared_use": doc('entity(ex:e, [xsi:type="x"])'),
 "xsi_redeclared_other": doc("entity(ex:e)", P + "prefix xsi <http://other/>\n"),
 "xsi_declared_standard": doc('entity(ex:e, [xsi:type="x"])', P + "prefix xsi <http://www.w3.org/2001/XMLSchema-instance#>\n"),
 "prefix_underscore": doc("entity(ex:e)", P + "prefix _ <http://u/>\n"),
 "prefix_with_slash": doc("entity(ex:e)", P + "prefix a/b <http://u/>\n"),
 "prefix_with_dot": doc("entity(a.b:e)", "prefix a.b <http://u/>\n"),
 "prefix_trailing_dot": doc("entity(ex:e)", P + "prefix a. <http://u/>\n"),
 "prefix_named_default": doc("entity(default:e)", "prefix default <http://u/>\n"),
 "prefix_named_prefix": doc("entity(prefix:e)", "prefix prefix <http://u/>\n"),
 "empty_iri_prefix": doc("entity(z:e)", "prefix z <>\n"),
 "empty_iri_default": doc("entity(e)", "default <>\n"),
 "iri_with_space": doc("entity(z:e)", "prefix z <http://a b/>\n"),
 "iri_with_nbsp": doc("entity(z:e)", "prefix z <http://a\xa0b/>\n"),
 "decl_after_statement": doc("entity(ex:e)\nprefix z <http://z/>"),
 "undeclared_prefix": doc("entity(zz:e)"),
 # whitespace, comments, encoding
 "bom": "\ufeff" + doc("entity(ex:e)"),
 "nbsp_whitespace": doc("entity(ex:e)\xa0"),
 "formfeed_whitespace": doc("entity(ex:e)\x0c"),
 "vtab_whitespace": doc("entity(ex:e)\x0b"),
 "u2028_whitespace": doc("entity(ex:e)\u2028"),
 "nel_whitespace": doc("entity(ex:e)\u0085"),
 "cr_only_lines": doc("entity(ex:e)").replace("\n", "\r"),
 "line_comment_eof": doc("entity(ex:e)") + "// trailing",
 "block_comment": doc("/* c */ entity(ex:e) // x"),
 "unterminated_comment": doc("entity(ex:e) /* oops"),
 "nul_char": doc("entity(ex:e)\x00"),
 # strings and literals
 "string_escapes": doc(r'entity(ex:e, [ex:k="a\tb\n\"q\" \'s\' \\"])'),
 "string_bad_escape": doc(r'entity(ex:e, [ex:k="a\qb"])'),
 "string_unicode_escape": doc(r'entity(ex:e, [ex:k="a\u0041"])'),
 "string_raw_newline": doc('entity(ex:e, [ex:k="a\nb"])'),
 "long_string": doc('entity(ex:e, [ex:k="""a\n"b" c"""])'),
 "long_string_four_quotes": doc('entity(ex:e, [ex:k="""a""""])'),
 "langtag": doc('entity(ex:e, [ex:k="x"@en-GB])'),
 "langtag_space_before": doc('entity(ex:e, [ex:k="x" @en])'),
 "langtag_trailing_dash": doc('entity(ex:e, [ex:k="x"@en-])'),
 "langtag_digits": doc('entity(ex:e, [ex:k="x"@123])'),
 "langtag_long_subtag": doc('entity(ex:e, [ex:k="x"@abcdefghijk-abcdefghijkl])'),
 "lang_and_type": doc('entity(ex:e, [ex:k="x"@en %% xsd:string])'),
 "int_literal": doc("entity(ex:e, [ex:k=42])"),
 "int_negative": doc("entity(ex:e, [ex:k=-42])"),
 "int_leading_zero": doc("entity(ex:e, [ex:k=007])"),
 "int_huge": doc("entity(ex:e, [ex:k=99999999999999999999])"),
 "int_beyond_i32": doc("entity(ex:e, [ex:k=3000000000])"),
 "typed_int_bad": doc('entity(ex:e, [ex:k="abc" %% xsd:int])'),
 "typed_int_spaces": doc('entity(ex:e, [ex:k=" 5 " %% xsd:int])'),
 "typed_double_bad": doc('entity(ex:e, [ex:k="abc" %% xsd:double])'),
 "typed_bool_bad": doc('entity(ex:e, [ex:k="maybe" %% xsd:boolean])'),
 "typed_bool_one": doc('entity(ex:e, [ex:k="1" %% xsd:boolean])'),
 "typed_string": doc('entity(ex:e, [ex:k="x" %% xsd:string])'),
 "typed_anyuri": doc('entity(ex:e, [ex:k="http://x/" %% xsd:anyURI])'),
 "typed_datetime_ok": doc('entity(ex:e, [ex:k="2012-01-01T00:00:00Z" %% xsd:dateTime])'),
 "typed_datetime_bad_month": doc('entity(ex:e, [ex:k="2012-13-01T00:00:00" %% xsd:dateTime])'),
 "typed_datetime_date_only": doc('entity(ex:e, [ex:k="2012-01-01" %% xsd:dateTime])'),
 "typed_datetime_space": doc('entity(ex:e, [ex:k="2012-01-01 00:00:00" %% xsd:dateTime])'),
 "typed_custom": doc('entity(ex:e, [ex:k="x" %% ex:thing])'),
 "typed_undeclared": doc('entity(ex:e, [ex:k="x" %% zz:thing])'),
 "typed_prov_qname": doc('entity(ex:e, [ex:k="ex:foo" %% prov:QUALIFIED_NAME])'),
 "typed_xsd_qname": doc('entity(ex:e, [ex:k="ex:foo" %% xsd:QName])'),
 "typed_prov_qname_unresolvable": doc('entity(ex:e, [ex:k="zz:foo" %% prov:QUALIFIED_NAME])'),
 "qname_literal": doc("entity(ex:e, [prov:type='prov:Plan'])"),
 "qname_literal_unresolvable": doc("entity(ex:e, [ex:k='zz:foo'])"),
 "qname_literal_empty": doc("entity(ex:e, [ex:k=''])"),
 "bare_name_value": doc("entity(ex:e, [ex:k=ex:v])"),
 "datetime_value": doc("entity(ex:e, [ex:k=2012-01-01T00:00:00])"),
 "dup_attr_pairs": doc('entity(ex:e, [ex:k="x", ex:k="x", ex:k="y"])'),
 "empty_attrs": doc("entity(ex:e, [])"),
 "attrs_trailing_comma": doc('entity(ex:e, [ex:k="x",])'),
 "two_attr_blocks": doc('entity(ex:e, [ex:k="x"], [ex:k="y"])'),
 "formal_named_attr": doc("wasGeneratedBy(ex:e, ex:a, -, [prov:activity='ex:b'])"),
 "formal_named_attr_same": doc("wasGeneratedBy(ex:e, ex:a, -, [prov:activity='ex:a'])"),
 "formal_named_attr_absent_formal": doc("wasGeneratedBy(ex:e, -, -, [prov:activity='ex:a'])"),
 "prov_time_attr_on_entity": doc('entity(ex:e, [prov:time="2012-01-01T00:00:00" %% xsd:dateTime])'),
 # dateTime arguments
 "dt_basic": doc("activity(ex:a, 2012-01-01T00:00:00, 2012-01-02T00:00:00Z)"),
 "dt_fraction_offset": doc("activity(ex:a, 2012-01-01T00:00:00.123456789+01:00, -)"),
 "dt_fraction_12_digits": doc("activity(ex:a, 2012-01-01T00:00:00.123456789012, -)"),
 "dt_year_10000": doc("activity(ex:a, 10000-01-01T00:00:00, -)"),
 "dt_negative_year": doc("activity(ex:a, -0044-03-15T00:00:00, -)"),
 "dt_year_0000": doc("activity(ex:a, 0000-01-01T00:00:00, -)"),
 "dt_hour_24": doc("activity(ex:a, 2012-01-01T24:00:00, -)"),
 "dt_second_60": doc("activity(ex:a, 2012-06-30T23:59:60Z, -)"),
 "dt_month_13": doc("activity(ex:a, 2012-13-01T00:00:00, -)"),
 "dt_feb_30": doc("activity(ex:a, 2012-02-30T00:00:00, -)"),
 "dt_offset_15h": doc("activity(ex:a, 2012-01-01T00:00:00+15:00, -)"),
 "dt_offset_14h": doc("activity(ex:a, 2012-01-01T00:00:00+14:00, -)"),
 "dt_in_name_position": doc("used(ex:a, 2012-01-01T00:00:00, -)"),
 "name_in_time_position": doc("used(ex:a, ex:e, ex:t)"),
 # statements
 "activity_one_time": doc("activity(ex:a, 2012-01-01T00:00:00)"),
 "activity_markers": doc("activity(ex:a, -, -)"),
 "element_marker_id": doc("entity(-)"),
 "element_trailing_comma": doc("entity(ex:e,)"),
 "gen_arity_2": doc("wasGeneratedBy(ex:e, ex:a)"),
 "gen_arity_1": doc("wasGeneratedBy(ex:e)"),
 "gen_marker_first": doc("wasGeneratedBy(-, ex:a, -)"),
 "gen_with_id": doc("wasGeneratedBy(ex:g; ex:e, ex:a, -)"),
 "gen_marker_id": doc("wasGeneratedBy(-; ex:e, ex:a, -)"),
 "gen_datetime_id": doc("wasGeneratedBy(2012-01-01T00:00:00; ex:e, ex:a, -)"),
 "derivation_3": doc("wasDerivedFrom(ex:e2, ex:e1, ex:a)"),
 "derivation_5": doc("wasDerivedFrom(ex:e2, ex:e1, ex:a, ex:g, ex:u)"),
 "delegation_2": doc("actedOnBehalfOf(ex:a2, ex:a1)"),
 "association_1": doc("wasAssociatedWith(ex:a)"),
 "start_4": doc("wasStartedBy(ex:a, ex:e, ex:a0, 2012-01-01T00:00:00)"),
 "start_3": doc("wasStartedBy(ex:a, ex:e, ex:a0)"),
 "member_with_id": doc("hadMember(ex:m; ex:c, ex:e)"),
 "member_with_attrs": doc('hadMember(ex:c, ex:e, [ex:k="x"])'),
 "spec_with_id": doc("specializationOf(ex:s; ex:e2, ex:e1)"),
 "alt_with_attrs": doc('alternateOf(ex:e2, ex:e1, [ex:k="x"])'),
 "mention_bare": doc("mentionOf(ex:e2, ex:e1, ex:b)"),
 "mention_prov": doc("prov:mentionOf(ex:e2, ex:e1, ex:b)"),
 "mention_marker": doc("mentionOf(ex:e2, ex:e1, -)"),
 "extensibility": doc("ex:foo(ex:e)"),
 "unknown_keyword": doc("foo(ex:e)"),
 "dictionary_stmt": doc("hadDictionaryMember(ex:d, ex:e, \"k\")"),
 "missing_rparen": doc("entity(ex:e"),
 "missing_end": "document\n" + P + "entity(ex:e)\n",
 "after_end": doc("entity(ex:e)") + "entity(ex:f)",
 "empty_document": "document\nendDocument",
 "empty_input": "",
 "no_document_keyword": P + "entity(ex:e)",
 # bundles
 "bundle_basic": doc("bundle ex:b\nentity(ex:e)\nendBundle"),
 "bundle_then_record": doc("bundle ex:b\nentity(ex:e)\nendBundle\nentity(ex:f)"),
 "bundle_nested": doc("bundle ex:b\nbundle ex:c\nendBundle\nendBundle"),
 "bundle_dup_id": doc("bundle ex:b\nendBundle\nbundle ex:b\nendBundle"),
 "bundle_own_prefix_id": doc("bundle z:b\nprefix z <http://z/>\nentity(z:e)\nendBundle"),
 "bundle_shadow_prefix_id": doc("bundle ex:b\nprefix ex <http://shadow/>\nentity(ex:e)\nendBundle"),
 "bundle_own_default_id": doc("bundle b\ndefault <http://bd/>\nentity(e)\nendBundle", D),
 "bundle_inherits_default": doc("bundle b\nentity(e)\nendBundle", D),
 "bundle_unterminated": doc("bundle ex:b\nentity(ex:e)"),
 "bundle_marker_id": doc("bundle -\nendBundle"),
 "bundle_prov_redeclared": doc("bundle ex:b\nprefix prov <http://other/>\nendBundle"),
 "same_record_twice": doc("entity(ex:e)\nentity(ex:e)"),

 # code point escapes, comments and line breaks
 "comment_slash_star_slash": "document /*/ endDocument\n",
 "comment_empty_block": "document /**/ endDocument\n",
 "crlf_line_comment": doc("entity(ex:e) // c").replace("\n", "\r\n"),
 "crlf_long_string": doc('entity(ex:e, [ex:k="""a\r\nb"""])'),
 "string_u_escape": doc(r'entity(ex:e, [ex:k="caf\u00E9"])'),
 "string_upper_u_escape": doc(r'entity(ex:e, [ex:k="\U0001F600"])'),
 "iri_u_escape": doc("entity(z:e)", r"prefix z <http://e/\u00E9>" + "\n"),
 "string_u_escape_lowercase": doc(r'entity(ex:e, [ex:k="caf\u00e9"])'),
 "string_u_escape_surrogate": doc(r'entity(ex:e, [ex:k="\uD800"])'),
 "string_u_escape_out_of_range": doc(r'entity(ex:e, [ex:k="\U00110000"])'),
 "string_u_escape_short": doc(r'entity(ex:e, [ex:k="\u12"])'),
 "iri_u_escape_forbidden": doc("entity(z:e)", r"prefix z <http://e/\u0020>" + "\n"),
 # literals
 "qname_literal_unterminated": doc("entity(ex:e, [ex:k='ex:v])"),
 "at_after_integer": doc("entity(ex:e, [ex:k=1 @en])"),
 "digit_datatype_default_first": doc('entity(ex:e, [ex:k="x" %% 123])', D + P),
 "int_below_i32": doc("entity(ex:e, [ex:k=-2147483649])"),
 "typed_prov_qname_not_a_name": doc('entity(ex:e, [ex:k="not a name" %% prov:QUALIFIED_NAME])'),
 "typed_prov_qname_space_in_local": doc('entity(ex:e, [ex:k="ex:a b" %% prov:QUALIFIED_NAME])'),
 # extensibility expressions
 "extensibility_set_form": doc('dictExt:hadMembers(mId; d, {("k1",e1), ("k2",e2), ("k3",e3)}, [])', X),
 "extensibility_nested_form": doc('dictExt:hadMembers(mid; d, dictExt:set(dictExt:pair("k1",e1), dictExt:pair("k2",e2)), [dictExt:uniqueKeys="true"])', X),
 "extensibility_in_bundle": doc("bundle ex:b\nex:foo(ex:e)\nendBundle"),
 "extensibility_after_bundle": doc("bundle ex:b\nendBundle\nex:foo(ex:e)"),
 "extensibility_undeclared_argument_prefix": doc("ex:foo(zz:a, 'zz:q', [zz:k=\"v\" %% zz:t])"),
 "extensibility_unclosed": doc("ex:foo(ex:e"),
 "extensibility_no_arguments": doc("ex:foo()"),
 "extensibility_trailing_comma": doc("ex:foo(ex:e,)"),
 "extensibility_empty_tuple": doc("ex:foo({})"),
 "extensibility_argument_after_attributes": doc("ex:foo(ex:e, [ex:k=1], ex:f)"),
 "extensibility_bare_nested_name": doc("ex:foo(set(1))"),
 "extensibility_marker_identifier": doc("ex:foo(-; a)"),
 "extensibility_attributes": doc('ex:foo(ex:e, [ex:k="v"])'),
 "extensibility_tuples_64": doc("ex:f(" + "(" * 64 + "ex:e" + ")" * 64 + ")"),
 "extensibility_tuples_65": doc("ex:f(" + "(" * 65 + "ex:e" + ")" * 65 + ")"),
 "extensibility_expressions_64": doc("ex:f(" + "ex:g(" * 64 + "ex:e" + ")" * 64 + ")"),
 "extensibility_expressions_65": doc("ex:f(" + "ex:g(" * 65 + "ex:e" + ")" * 65 + ")"),
}

target = Path(__file__).resolve().parent.parent / "provn" / "probes"
target.mkdir(parents=True, exist_ok=True)
for name, text in probes.items():
    with open(target / f"{name}.provn", "w", encoding="utf-8", newline="") as f:
        f.write(text)
print(len(probes), "probes written to", target)
